# 기본 이미지 설정
FROM openjdk:17-jdk-slim AS builder
LABEL authors="junpyohong"

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

# 의존성 설치 (캐싱을 위해)
RUN ./gradlew dependencies

# 프로젝트 파일 복사
COPY src src

# 실제 빌드 실행
RUN ./gradlew clean build -x test

# 최종 이미지 생성을 위한 멀티-스테이지 빌드
FROM openjdk:17-jdk-slim
COPY --from=builder /app/build/libs/*.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]